### ISSUE TITLE
SoftContains doing deep equal check instead of checking first parameter contains second parameter

### ISSUE THREAD

**Issue by zohebsiddique** [sarunya/soft-assert#3]
SoftContains is not working as expected as it is doing deep equal check instead of checking first parameter contains second parameter.

**Comment by sarunya** [comment]
Hi, Can you provide sample code/data where softContains doesnt work. This would help me to replicate and fix the issue

**Comment by zohebsiddique** [comment]
Following is what I was trying to run. Here I am checking whether the
sentence contains the name.


However, rather than doing the 'contains' check it's doing a deep equal check.

softContains('My Name is Zoheb', 'Zoheb', 'Message does not contain
expected name');

**Comment by ismaelcabreramartin** [comment]
Hello, I am getting the same issue. Here you have a sample:

    jsonAssertion.softContains("Avani Kaur", "Kaur", "Name should contain Kaur");

Message: 1 : key -> $             message: expected 'Avani Kaur' to deeply equal 'Kaur'

**Comment by sarunya** [comment]
Thanks for pointing out. This has been addressed in latest tag
